# Site settings
title: Austin Zentz
email: austin.zentz@gmail.com
description: "Austin Zentz is a developer and analyst for District of Columbia Public Schools."
url: "http://www.austinzentz.com"
baseurl: ""

# Build settings
markdown: kramdown
exclude: ['vendor']
port: 3000

sass:
  style: :compressed

gems:
  - jekyll-sitemap

collections:
  projects:
    output: true