# Site settings
title: Austin Zentz
email: austin.zentz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rails, data analysis, projects and musings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.austinzentz.com" # the base hostname & protocol for your site
github_username:  aust1nz
linkedin_username: austin.zentz
linkedin_url: austin-zentz/14/269/470

# Build settings
markdown: kramdown
exclude: ['vendor']
port: 3000

sass:
  style: :compressed

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

include: ['_projects']